### PR TITLE
Update to Astro v1.0 (rc)

### PR DESCRIPTION
**Pull request by barrenechea**
Hi! I'm just starting to play around with Astro. At first, I wanted to see if I could contribute something to https://github.com/Princesseuh/astro-social-images (which I just finished implementing with custom fonts and all, really awesome!), and at first, I went ahead and bumped Astro to an RC version, and then this dependency (astro-component-tester) started to fail on me.

Screen Shot 2022-07-30 at 11 04 33

The main issue gets fixed with 97b2333282269dd6796e11a2cc227a2d91068dd0, fixing the generated ESM output (and also adding `"type": "module"` @ package.json).
Before:
Screen Shot 2022-07-30 at 10 57 45

After:
Screen Shot 2022-07-30 at 10 57 59

The main issue is related to the RC versions of Astro using Vite 3 instead of Vite 2, and I guess the testing suite is more restrictive with "what dependencies are you using, and how are they built".

I also bumped all other deps, making sure everything works as expected (by using pnpm workspaces with `astro-social-images` and running its tests.

### CODE REVIEW

**Comment by barrenechea** [comment]
I've set `"astro": "^1.0.0-rc.1"` in the peer deps to not exclude rc1 and rc2, even though rc3 is the latest one. Not sure if you agree with it?

And package.json's version should be bumped to something as well. 0.6.0? I could add it to this PR, no issues 😄

**Comment by Princesseuh** [comment]
Hello! Thank you for this PR.

Everything looks good to me, however I just worry about the CJS compatibility because of the `type: module`. CJS compatibility is unfortunately important because of Jest (see https://github.com/Princesseuh/astro-component-tester/pull/5 )

If you have time, could you test if everything still work using Jest? Otherwise I can take care of it

**Comment by barrenechea** [comment]
I'll do! No prob 😊

**Comment by barrenechea** [comment]
Ok, so I tweaked `astro-social-images` to use Jest instead of Mocha and make sure everything works as expected (just for testing, IMO Mocha works best for ESM 😄).
Ran two tests:

CommonJS (running `jest --testTimeout 15000`):
Screen Shot 2022-07-30 at 13 00 47

ESM (running `NODE_OPTIONS=--experimental-vm-modules jest --testTimeout 15000`):
Screen Shot 2022-07-30 at 12 59 42

It seems to be all good at least on Jest v28. Want me to test it on v27 @Princesseuh ?

**Comment by Princesseuh** [comment]
Seems good to me, I don't know much about Jest, but I don't see any reasons why it wouldn't work on 27. Thank you for testing!

**Pull request merged**
